---
version: '2'
networks:
  kafka_network:
    name: kafka-network
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - kafka_network
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  zookeeper2:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper2
    container_name: zookeeper2
    networks:
      - kafka_network
    ports:
      - "2182:2182"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:6.2.0
    hostname: broker
    container_name: broker
    networks:
      - kafka_network
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
  broker2:
    image: confluentinc/cp-kafka:6.2.0
    hostname: broker2
    container_name: broker2
    networks:
      - kafka_network
    depends_on:
      - zookeeper2
    ports:
      - "9093:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper2:2182"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:29093
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"

  connect:
    image: confluentinc/cp-kafka-connect:6.2.0
    hostname: connect
    container_name: connect
    networks:
      - kafka_network
    depends_on:
      - zookeeper
      - broker
    ports:
      - "28082:28082"
      - "9998:9998"
      - "9999:9999"
      - "18889:18889"
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=broker:29092
      - CONNECT_REST_PORT=28082
      - CONNECT_GROUP_ID="quickstart"
      - CONNECT_CONFIG_STORAGE_TOPIC=quickstart_config
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_OFFSET_STORAGE_TOPIC=quickstart_offsets
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_STATUS_STORAGE_TOPIC=quickstart_status
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.converters.ByteArrayConverter
      - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.converters.ByteArrayConverter
      - CONNECT_REST_ADVERTISED_HOST_NAME="localhost"
      - CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY=All
